### ISSUE TITLE
python manage.py run error

### ISSUE THREAD

**Issue by gclsoft** [defshine/cleanblog#1]
```
apple@bogon ~/n/cleanblog> python3 run.py 
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from app import create_app
  File "/Users/apple/node/cleanblog/app/__init__.py", line 2, in <module>
    from models import db
ImportError: No module named 'models'
```

or python2.7 error 

```
apple@bogon ~/n/cleanblog> python manage.py run
Traceback (most recent call last):
  File "manage.py", line 6, in <module>
    app = create_app()
  File "/Users/apple/node/cleanblog/app/__init__.py", line 19, in create_app
    create_admin(app)
  File "/Users/apple/node/cleanblog/app/admin/__init__.py", line 8, in create_admin
    admin.add_view(UserView(User))
  File "/Library/Python/2.7/site-packages/flask_admin/contrib/mongoengine/view.py", line 219, in __init__
    super(ModelView, self).__init__(model, name, category, endpoint, url)
  File "/Library/Python/2.7/site-packages/flask_admin/model/base.py", line 515, in __init__
    self._refresh_cache()
  File "/Library/Python/2.7/site-packages/flask_admin/contrib/mongoengine/view.py", line 234, in _refresh_cache
    super(ModelView, self)._refresh_cache()
  File "/Library/Python/2.7/site-packages/flask_admin/model/base.py", line 536, in _refresh_cache
    self._create_form_class = self.get_create_form()
  File "/Library/Python/2.7/site-packages/flask_admin/model/base.py", line 783, in get_create_form
    return self.get_form()
  File "/Library/Python/2.7/site-packages/flask_admin/model/base.py", line 775, in get_form
    return self.scaffold_form()
  File "/Library/Python/2.7/site-packages/flask_admin/contrib/mongoengine/view.py", line 382, in scaffold_form
    extra_fields=self.form_extra_fields)
  File "/Library/Python/2.7/site-packages/flask_admin/contrib/mongoengine/form.py", line 237, in get_form
    field = converter.convert(model, p, field_args.get(name))
  File "/Library/Python/2.7/site-packages/flask_admin/contrib/mongoengine/form.py", line 64, in convert
    'description': field.help_text or '',
AttributeError: 'StringField' object has no attribute 'help_text'
```

**Comment by defshine** [comment]
This is the problem of flask-mongoengine.
See this http://stackoverflow.com/questions/34161163/python-wtf-attributeerror-objectidfield-object-has-no-attribute-help-text
you can use the previous version,when I develop this app, I use
flask-mongoengine (0.7.1)
mongoengine (0.8.7)
Also this app only run under python 2.7
